schema_version = "1.0.0"
id = "geomviz"
version = "0.0.1"
name = "Geomviz"
tagline = "Use Blender as a geometric algebra plotting tool"
maintainer = "Joseph Wilson <jo.alex.w@gmail.com>"
type = "add-on"
website = "https://github.com/Jollywatt/Geomviz"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
