[project]
name = "Geomviz"
authors = ["jollywatt <jo.alex.w@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
blend = "/Applications/Blender.app/Contents/MacOS/Blender"

[dependencies]
python = ">=3.11,<3.12"
bson = ">=0.5.9,<0.6"
ipython = ">=8.26.0,<8.27"
typos = ">=1.31.0,<2"

[pypi-dependencies]
bpy = "*"
