name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.44.0

      - name: Run build scripts
        run: pixi run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-zips
          path: |
            dist/*

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
